name: "Feature request"
description: "Suggest an idea for this project"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "## Feature Request\nPlease describe your feature idea in detail."
  - type: input
    id: summary
    attributes:
      label: "Summary"
      description: "A short summary of your feature request."
      placeholder: "Auto update stacks, improved UI, etc."
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: "Detailed description"
      description: "Describe the feature, its purpose, and any relevant context."
      placeholder: "What problem does it solve? How should it work?"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: "Alternatives considered"
      description: "Have you considered any alternative solutions or workarounds?"
      placeholder: "Other plugins, manual steps, etc."
    validations:
      required: false
